
import React, { useState } from 'react';

const SeoArticle: React.FC = () => {
  const [isOpen, setIsOpen] = useState(false);

  const articleSchema = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "The Ultimate Guide to Small Claims Court: Process, Filing, and Tips",
    "alternativeHeadline": "How to File a Small Claims Lawsuit Without a Lawyer",
    "image": "https://doodax.com/small-claims-guide.jpg",
    "author": {
      "@type": "Person",
      "name": "HSINI MOHAMED",
      "url": "https://github.com/hsinidev"
    },
    "publisher": {
        "@type": "Organization",
        "name": "Doodax",
        "logo": {
            "@type": "ImageObject",
            "url": "https://doodax.com/logo.png"
        }
    },
    "datePublished": "2023-10-27",
    "dateModified": new Date().toISOString().split('T')[0],
    "description": "A comprehensive guide to navigating small claims court, including how to file, evidence preparation, and demand letters. Generated by Doodax.",
    "mainEntityOfPage": {
         "@type": "WebPage",
         "@id": "https://doodax.com/"
    }
  };

  const howToSchema = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    "name": "How to File a Small Claims Court Statement",
    "description": "Step-by-step guide to generating and filing a small claims statement of claim using Doodax.",
    "step": [
      {
        "@type": "HowToStep",
        "name": "Enter Party Details",
        "text": "Input the Plaintiff (your) and Defendant (opposing party) information accurately into the Doodax form."
      },
      {
        "@type": "HowToStep",
        "name": "Describe the Claim",
        "text": "Detail the reason for the claim, the specific amount owed, and the date the incident occurred."
      },
      {
        "@type": "HowToStep",
        "name": "Generate Document",
        "text": "Click the generate button to create a professional Statement of Claim PDF."
      },
      {
        "@type": "HowToStep",
        "name": "File with Court",
        "text": "Print 3 copies and take them to your local county clerk to officially file the lawsuit."
      }
    ]
  };

  return (
    <article className="max-w-5xl mx-auto px-4 mb-12 relative z-20">
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />
        
        <div className="glass-panel rounded-2xl p-8 md:p-12 shadow-lg">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-8 font-heading text-center">The Ultimate Guide to Small Claims Court</h2>
            
            {/* Content Container with height constraints */}
            <div className={`relative transition-all duration-700 ease-in-out overflow-hidden ${isOpen ? 'max-h-full' : 'max-h-24'}`}>
                <div className="prose prose-lg prose-indigo max-w-none text-gray-700">
                    
                    {/* Introduction */}
                    <p className="lead text-xl mb-6">
                        Navigating the judicial system in the United States can often feel like traversing a labyrinth without a map. For many individuals and small business owners, the cost of hiring an attorney to resolve minor disputes far outweighs the potential recovery. This is where <strong>Small Claims Court</strong>—often called the "People's Court"—shines. It provides a streamlined, accessible, and relatively inexpensive venue for resolving civil disputes involving limited amounts of money.
                    </p>

                    {/* Table of Contents */}
                    <nav className="bg-indigo-50 p-8 rounded-xl my-10 border border-indigo-100 not-prose">
                        <h3 className="text-2xl font-bold text-indigo-900 mb-6">Table of Contents</h3>
                        <ul className="grid md:grid-cols-2 gap-4 text-indigo-700 font-medium">
                            <li><a href="#what-is-small-claims" className="hover:underline hover:text-indigo-900">1. What is Small Claims Court?</a></li>
                            <li><a href="#jurisdictional-limits" className="hover:underline hover:text-indigo-900">2. Jurisdictional Limits by State</a></li>
                            <li><a href="#before-filing" className="hover:underline hover:text-indigo-900">3. Steps Before Filing</a></li>
                            <li><a href="#how-to-file" className="hover:underline hover:text-indigo-900">4. The Filing Process</a></li>
                            <li><a href="#court-day" className="hover:underline hover:text-indigo-900">5. Preparing for Your Court Day</a></li>
                            <li><a href="#collecting-judgment" className="hover:underline hover:text-indigo-900">6. Collecting Your Judgment</a></li>
                            <li><a href="#faq" className="hover:underline hover:text-indigo-900">7. Frequently Asked Questions</a></li>
                        </ul>
                    </nav>

                    <h3 id="what-is-small-claims" className="text-2xl font-bold text-gray-900 mt-12 mb-4">1. What is Small Claims Court?</h3>
                    <p>
                        Small claims court is a specific division of the county court system designed to hear civil cases between private litigants. Its primary purpose is to provide a forum for resolving disputes that involve relatively small amounts of money (damages) without the procedural complexity and formal rules of evidence found in higher courts.
                    </p>
                    <p>
                        In most jurisdictions, you are not required to have a lawyer. In fact, some states (like California and Michigan) actively forbid attorneys from representing parties in small claims court, ensuring a level playing field where individuals speak for themselves.
                    </p>

                    <h3 id="jurisdictional-limits" className="text-2xl font-bold text-gray-900 mt-12 mb-4">2. Jurisdictional Limits (How Much Can You Sue For?)</h3>
                    <p>
                        One of the most critical factors in determining if small claims court is right for you is the <strong>dollar limit</strong> (jurisdictional limit) on claims. This varies significantly from state to state. If your claim exceeds this limit, you must either lower your claim amount to fit within the limit or file your case in a higher civil court (where procedures are more complex).
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>$2,500 - $5,000:</strong> Kentucky, Rhode Island.</li>
                        <li><strong>$5,000 - $10,000:</strong> New York, California (for individuals), Florida, Texas, Pennsylvania.</li>
                        <li><strong>$15,000 - $25,000:</strong> Delaware, Tennessee.</li>
                    </ul>
                    <p><em>Note: These limits change frequently. Always verify with your local court clerk.</em></p>

                    <h3 id="before-filing" className="text-2xl font-bold text-gray-900 mt-12 mb-4">3. Essential Steps Before Filing a Lawsuit</h3>
                    <p>Before you pay the filing fee, you must ensure you have a valid case and have attempted to resolve it outside of court.</p>
                    
                    <h4 className="text-xl font-semibold mt-6 mb-2">The Demand Letter</h4>
                    <p>
                        Almost every judge will ask, "Did you ask the defendant to pay you before suing?" Sending a formal <strong>Demand Letter</strong> is often a legal requirement. It serves as evidence that you attempted to resolve the dispute in good faith. Your letter should include:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>A clear statement of facts.</li>
                        <li>The specific amount of money demanded.</li>
                        <li>A deadline for payment (usually 10-14 days).</li>
                        <li>A statement that legal action will follow if payment is not made.</li>
                    </ul>
                    <p><em>Tip: Send this via Certified Mail with Return Receipt Requested so you have proof of delivery.</em></p>

                    <h3 id="how-to-file" className="text-2xl font-bold text-gray-900 mt-12 mb-4">4. The Filing Process: Step-by-Step</h3>
                    
                    <p><strong>Step 1: Determine the Correct Venue</strong><br/>
                    You cannot just file in any court. You typically must sue in the county where the Defendant lives, where the business is located, or where the incident occurred.</p>

                    <p><strong>Step 2: Complete the "Statement of Claim"</strong><br/>
                    This is the form generated by <strong>Doodax</strong>. It identifies the Plaintiff (you), the Defendant, and the reason for the lawsuit.</p>

                    <p><strong>Step 3: Pay the Filing Fee</strong><br/>
                    Fees range from $30 to $150 depending on your state and the amount of your claim. Low-income filers can often request a "Fee Waiver."</p>

                    <p><strong>Step 4: Serve the Defendant</strong><br/>
                    "Service of Process" is notifying the defendant they are being sued. You cannot do this yourself. You must use:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>The Sheriff's Office.</li>
                        <li>A private Process Server.</li>
                        <li>Certified Mail (allowed in some states).</li>
                        <li>A disinterested third party over 18.</li>
                    </ul>

                    <h3 id="court-day" className="text-2xl font-bold text-gray-900 mt-12 mb-4">5. Preparing for Your Court Day</h3>
                    <p>
                        Preparation is 90% of the battle. When your day in court arrives, be punctual, dress professionally, and bring three copies of all evidence (one for you, one for the judge, one for the defendant).
                    </p>
                    <h4 className="text-xl font-semibold mt-6 mb-2">Types of Evidence</h4>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Contracts/Leases:</strong> Signed agreements are powerful evidence.</li>
                        <li><strong>Photos/Videos:</strong> Visual proof of damage or poor workmanship.</li>
                        <li><strong>Receipts/Invoices:</strong> Proof of payment or costs incurred.</li>
                        <li><strong>Communication Logs:</strong> Printed emails, text messages (with timestamps), and phone logs.</li>
                        <li><strong>Witnesses:</strong> People who saw the incident firsthand.</li>
                    </ul>

                    <h3 id="collecting-judgment" className="text-2xl font-bold text-gray-900 mt-12 mb-4">6. Collecting Your Judgment</h3>
                    <p>
                        Winning the lawsuit does not mean the court writes you a check. If the defendant refuses to pay the judgment, you must enforce it. Common methods include:
                    </p>
                    <ul className="list-disc pl-6 space-y-2">
                        <li><strong>Wage Garnishment:</strong> Taking a portion of their paycheck (state laws vary).</li>
                        <li><strong>Bank Levy:</strong> Seizing funds directly from their bank account.</li>
                        <li><strong>Property Lien:</strong> Placing a lien on their real estate.</li>
                    </ul>

                    <h3 id="faq" className="text-2xl font-bold text-gray-900 mt-12 mb-4">7. Frequently Asked Questions (FAQ)</h3>
                    
                    <div className="space-y-6 mt-6">
                        <div>
                            <h4 className="font-bold text-lg text-indigo-900">Can I sue a corporation in small claims court?</h4>
                            <p>Yes. You must ensure you have the correct legal name of the business (often found on the Secretary of State's website) and serve their "Registered Agent."</p>
                        </div>
                        <div>
                            <h4 className="font-bold text-lg text-indigo-900">What happens if the defendant doesn't show up?</h4>
                            <p>If the defendant was properly served and fails to appear, you typically win by "Default Judgment." You still must prove to the judge that you are entitled to the money.</p>
                        </div>
                        <div>
                            <h4 className="font-bold text-lg text-indigo-900">Is there a statute of limitations?</h4>
                            <p>Yes. You have a limited time to sue. For written contracts, it's often 4-6 years; for property damage or personal injury, it might be 2-3 years. Check your state laws immediately.</p>
                        </div>
                    </div>

                    <aside className="mt-12 p-6 bg-yellow-50 border-l-4 border-yellow-400 text-yellow-800 rounded-r-lg">
                        <strong>Disclaimer:</strong> Doodax is a document generation tool, not a law firm. The information provided in this article is for general educational purposes and does not constitute legal advice. Laws vary by jurisdiction and change over time. Always consult with a qualified attorney regarding your specific legal situation.
                    </aside>

                </div>

                {/* Gradient Fade for closed state */}
                {!isOpen && (
                   <div className="absolute bottom-0 left-0 w-full h-20 bg-gradient-to-t from-white to-transparent pointer-events-none"></div>
                )}
            </div>
          
            {/* Toggle Button */}
            <div className="mt-8 text-center relative z-30">
                <button 
                    onClick={() => setIsOpen(!isOpen)} 
                    className="group flex items-center gap-2 mx-auto px-8 py-3 bg-indigo-600 hover:bg-indigo-700 text-white font-bold rounded-full transition-all shadow-lg hover:shadow-indigo-500/30 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
                    aria-expanded={isOpen}
                    aria-label={isOpen ? "Read Less" : "Read Full Guide"}
                >
                    {isOpen ? 'Read Less' : 'Read Full Guide'}
                    <svg 
                        className={`w-5 h-5 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`} 
                        fill="none" 
                        stroke="currentColor" 
                        viewBox="0 0 24 24"
                    >
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
                    </svg>
                </button>
            </div>
        </div>
    </article>
  );
};

export default SeoArticle;
